// Copyright (c) 2026 Robin Mordasiewicz. MIT License.

/**
 * Generator for the runtime namespace-profiles map.
 *
 * Bakes the authoritative resource→namespace-profile map (namespace_profiles.json,
 * the single source of truth) into src/generated/namespaceProfiles.ts as a typed
 * constant. This makes the map available at RUNTIME so that manually-defined
 * resource types (which have no generated spec entry) resolve their namespace
 * profile from the map instead of hardcoding it — closing the drift gap where a
 * hand-authored profile could contradict upstream (see issue #726).
 *
 * The map is normalized through the exact same loadNamespaceProfiles() path used
 * to assign profiles to generated resource types, so the runtime map and the
 * generated resource types can never diverge.
 */

import * as fs from 'node:fs';
import { loadNamespaceProfiles } from './spec-parser';

/**
 * Load the authoritative namespace_profiles.json map and write it to a generated
 * TypeScript module as NAMESPACE_PROFILES_MAP plus a resolveNamespaceProfileForKey
 * helper. Throws (via loadNamespaceProfiles) if the map is missing or invalid.
 *
 * @param namespaceProfilesPath - Path to the authoritative namespace_profiles.json
 * @param outputPath - Path for the generated TypeScript file
 */
export function writeNamespaceProfilesFile(namespaceProfilesPath: string, outputPath: string): void {
  const map = loadNamespaceProfiles(namespaceProfilesPath);
  const mapJson = JSON.stringify(map, null, 2);
  const resourceCount = Object.keys(map.resources).length;

  const content = `/**
 * Auto-generated authoritative namespace-profile map.
 * DO NOT EDIT - This file is generated by scripts/generate-resource-types.ts
 *
 * Single source of truth for which namespaces a resource type may live in.
 * Explicitly classified resources: ${resourceCount}.
 */

import type { NamespaceProfile } from './resourceTypesBase';

/**
 * Flat resource→namespace-profile map. A resource resolves to
 * resources[resourceKey], falling back to \`default\` when not explicitly listed.
 */
export interface NamespaceProfilesMap {
  default: NamespaceProfile;
  resources: Record<string, NamespaceProfile>;
}

export const NAMESPACE_PROFILES_MAP: NamespaceProfilesMap = ${mapJson};

/**
 * Resolve the authoritative namespace profile for a resource key: the explicit
 * map entry if present, otherwise the map default. This mirrors the build-time
 * resolution applied to generated resource types, so manually-defined types
 * (with no generated spec) get the same map-driven profile — never a hardcoded one.
 *
 * @param key - The resource key (e.g., 'user')
 * @returns The resolved namespace profile
 */
export function resolveNamespaceProfileForKey(key: string): NamespaceProfile {
  return NAMESPACE_PROFILES_MAP.resources[key] ?? NAMESPACE_PROFILES_MAP.default;
}
`;

  fs.writeFileSync(outputPath, content, 'utf-8');
  console.log(`Generated: ${outputPath} (${resourceCount} explicit profiles)`);
}
