// Copyright (c) 2026 Robin Mordasiewicz. MIT License.

/**
 * Resource coverage snapshots (issue #727).
 *
 * The extension surfaces a *curated* subset of resource types: only keys present
 * in RESOURCE_TYPE_OVERRIDES (which carry hand-authored UI metadata such as an
 * icon) appear in RESOURCE_TYPES. Resources classified in the authoritative
 * namespace map but not surfaced were previously dropped **silently**.
 *
 * These snapshots make the gap explicit so it can never drift silently. The
 * guard test in `resourceCoverage.test.ts` asserts the live gap equals the
 * snapshot; when upstream adds/renames/removes a resource, the test fails and a
 * human must make a conscious decision:
 *   - surface it: add an entry to RESOURCE_TYPE_OVERRIDES (with UI metadata), or
 *   - acknowledge it: refresh the snapshots below.
 *
 * DO NOT edit the arrays by hand — regenerate with:
 *   npx ts-node scripts/update-resource-coverage.ts
 */

/**
 * Resources classified in the authoritative namespace map that are NOT visible
 * in the curated RESOURCE_TYPES tree. Sorted. This is the primary no-silent-drops
 * guard: the set must change only via a reviewed regeneration.
 */
export const KNOWN_INVISIBLE_MAP_RESOURCES: readonly string[] = [
  'address_allocator',
  'advertise_policy',
  'ai_gateway',
  'ai_policy',
  'alert',
  'alert_policy_set',
  'analytics_query',
  'api_credential_api_token',
  'api_endpoint',
  'api_rate_limit',
  'app_api_group',
  'app_setting',
  'app_type',
  'audit_log',
  'authentication',
  'authentication_policy',
  'authorization_server',
  'bigip_device',
  'bigip_http_proxy',
  'bigip_pool',
  'blindfold_secret',
  'bot_defense_instance',
  'bucket',
  'ca_certificate',
  'cdn_cache_rule',
  'cdn_origin_pool',
  'cdn_purge_command',
  'cminstance',
  'contact',
  'container_registry',
  'crl',
  'customer_support',
  'dashboard',
  'data_classification',
  'data_export',
  'data_group',
  'dc_cluster_group',
  'ddos_mitigation_rule',
  'ddos_protection',
  'dns_compliance_checks',
  'dns_domain',
  'endpoint',
  'external_connector',
  'fast_acl',
  'fast_acl_rule',
  'filter_set',
  'fleet_config',
  'geo_location_set',
  'global_network',
  'ike1',
  'ike2',
  'ike_phase1_profile',
  'ike_phase2_profile',
  'insight_query',
  'interface',
  'ip_prefix_set',
  'k8s_cluster',
  'k8s_cluster_role_binding',
  'k8s_pod_security_admission',
  'k8s_pod_security_policy',
  'known_label',
  'known_label_key',
  'label',
  'label_group',
  'log_receiver',
  'malicious_user_detection',
  'malicious_user_rule',
  'marketplace_item',
  'metrics_receiver',
  'mitigation_policy',
  'mk8s_cluster',
  'namespace',
  'namespace_role',
  'namespace_role_binding',
  'network_interface',
  'network_policy_rule',
  'network_policy_set',
  'network_policy_view',
  'nfv_service',
  'nginx_config',
  'nginx_upstream',
  'node_config',
  'object_store',
  'otp_policy',
  'physical_k8s_site',
  'pod_security_policy',
  'policy_document',
  'protocol_inspection',
  'protocol_policer',
  'proxy',
  'quota',
  'rate_limit_threshold',
  'registration',
  'registration_token',
  'report_config',
  'saved_query',
  'secret',
  'segment',
  'service_discovery',
  'service_policy_rule',
  'session',
  'shape_app_firewall',
  'shape_recognizer',
  'site',
  'site_config',
  'site_mesh',
  'software_version',
  'srv6_network_slice',
  'static_asset',
  'subnet',
  'subscription',
  'support_case',
  'telemetry_receiver',
  'tenant',
  'tenant_configuration',
  'tenant_settings',
  'threat_campaign_policy',
  'threat_category',
  'token',
  'tpm_api_key',
  'tpm_category',
  'tpm_manager',
  'tunnel',
  'ui_component',
  'upgrade_os',
  'usage_report',
  'usb_policy',
  'user_profile',
  'user_role',
  'views_advertise_policy',
  'views_aws_tgw_site',
  'views_aws_vpc_site',
  'views_azure_vnet_site',
  'views_gcp_vpc_site',
  'views_physical_k8s_site',
  'views_voltstack_site',
  'virtual_host',
  'voltshare_admin_policy',
  'vpm_config',
  'waf',
  'workload',
  'workload_flavor',
];

/**
 * Subset of the above: resources in the namespace map that the generator cannot
 * parse from the domain specs at all (no consumable resource type is produced).
 * These require an upstream spec/parser change before they could ever be
 * surfaced. Tracked separately so a growing parse gap is visible in CI.
 */
export const KNOWN_PARSE_GAP_RESOURCES: readonly string[] = [
  'ai_gateway',
  'ai_policy',
  'alert_policy_set',
  'analytics_query',
  'api_credential_api_token',
  'api_endpoint',
  'api_rate_limit',
  'authentication_policy',
  'bigip_device',
  'bigip_pool',
  'blindfold_secret',
  'bot_defense_instance',
  'bucket',
  'ca_certificate',
  'cdn_origin_pool',
  'dashboard',
  'data_classification',
  'data_export',
  'ddos_mitigation_rule',
  'ddos_protection',
  'fleet_config',
  'global_network',
  'insight_query',
  'interface',
  'label',
  'label_group',
  'malicious_user_detection',
  'malicious_user_rule',
  'marketplace_item',
  'metrics_receiver',
  'mitigation_policy',
  'mk8s_cluster',
  'namespace',
  'namespace_role_binding',
  'nginx_config',
  'nginx_upstream',
  'node_config',
  'object_store',
  'otp_policy',
  'physical_k8s_site',
  'pod_security_policy',
  'policy_document',
  'rate_limit_threshold',
  'registration_token',
  'saved_query',
  'secret',
  'service_discovery',
  'session',
  'shape_app_firewall',
  'shape_recognizer',
  'site_config',
  'site_mesh',
  'software_version',
  'static_asset',
  'subscription',
  'support_case',
  'telemetry_receiver',
  'tenant',
  'tenant_settings',
  'threat_campaign_policy',
  'threat_category',
  'ui_component',
  'upgrade_os',
  'usage_report',
  'user',
  'user_profile',
  'views_advertise_policy',
  'views_aws_tgw_site',
  'views_aws_vpc_site',
  'views_azure_vnet_site',
  'views_gcp_vpc_site',
  'views_physical_k8s_site',
  'views_voltstack_site',
  'vpm_config',
  'waf',
];
